#!/usr/bin/env bash
# Sends a file to the server
if [ $# -lt 4 ]; then
        echo "Usage ./transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi
local_file="$1"
server_ip="$2"
username="$3"
ssh_key="$4"
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$local_file" "$username@$server_ip:~/"
