#!/usr/bin/env bash
# installs Nginx in server
sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i 's/listen80;/listen 80 default_server;/' /etc/nginx/sites-available/default
echo "Hello World!" > var/www/html/index.html
sudo /etc/init.d/nginx restart
