#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i 's/listen80;/linsten 80 default_server;/' /etc/nginx/sites-available/default
sudo echo "Hello World!" > index.html
sudo /etc/init.d/nginx restart
