#!/usr/bin/env bash
# Implements if control statement in while loop
count=1
text="Best School"
while [ $count -le 10 ]
do
        if [ $count -ne 9 ]; then
                echo "$text"
        else
                echo "$text"
                echo "Hi"
        fi
        ((count++))
done


