#!/usr/bin/env bash
# Combines use of for loop and if else
text="Best School"
count=1
while [ $count -le 10 ]
do
        if [ $count -eq 4 ]; then
                echo "bad luck"
        elif [ $count -eq 8 ]; then
                echo "good luck"
        else
                echo "$text"
        fi
        ((count++))
done

