#!/usr/bin/env bash
# Configures Ubuntu server
NEW_IP="127.0.0.2"
NEW_FACEBOOK_IP="8.8.8.8"
sudo cp /etc/hosts /etc/hosts.bak #Creates a backup
sudo sed -i "s/127.0.0.1/127.0.0.2/g" /etc/hosts
echo "$NEW_FACEBOOK_IP     facebook.com" >> /etc/hosts
echo "$NEW_IP   localhost" >> /etc/hosts
